/*************************************************************************************************************
 * @name			DeactivateUserProcessor
 * @author			Konstantin Murin <konstantin.murin@synebo.io>
 * @date			10 / 11 / 2023
 * @description		Deactivation process
**************************************************************************************************************/
public with sharing class DeactivateUserProcessor implements OktaUserProcessorInterface {
    
    public void processOktaUser(OktaRequestWrapper.Events event) {
        // Process upsert
    }
}