/*************************************************************************************************************
 * @name			UpsertUserProcessor
 * @author			Konstantin Murin <konstantin.murin@synebo.io>
 * @date			10 / 11 / 2023
 * @description		Upsert process
**************************************************************************************************************/
public with sharing class UpsertUserProcessor implements OktaUserProcessorInterface {
    
    public void processOktaUser(OktaRequestWrapper.Events event) {
        // Process upsert
    }
}